[package]
name = "celuloid_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
gphoto2 = "3.2.1"
rppal = "0.14.1"

[profile.release]
opt-level=3
lto=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

